exports.userData=[
{
    userId:"123gmail",
        name:"vinay",
        email:"vinal@gmail.com",
        password:"1234567987",
        userType:"CUSTOMER",
        userStatus:"APPROVED"
},
{
    userId:"123abhi",
    name:"abhi",
    email:"abhi@gmail.com",
    password:"3213214321",
    userType:"CUSTOMER",
    userStatus:"APPROVED"
}
]